name: Deploy to Docker

on:
  push:
    tags:        
      - v*
    branches:
      - "!dependabot/**"
  pull_request:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: registry.frozensoftsoftware.com
          username: ${{ secrets.FSS_REGISTRY_USERNAME }}
          password: ${{ secrets.FSS_REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: registry.frozensoftsoftware.com/eirik-landingsside:latest
